{% set name = "swmr-tools" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/swmr_tools-{{ version }}.tar.gz
  sha256: c003e0dd54dbde6750d3581725b97757126cc89aef4083c1892d7ad240ec42d5

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - numpy
    - h5py
    - python-blosc
    - python >={{ python_min }}

test:
  imports:
    - swmr_tools
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/DiamondLightSource/python-swmrtools
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python tools for working with HDF5 SWMR files
  doc_url: https://python-swmrtools.readthedocs.io
  dev_url: https://github.com/DiamondLightSource/python-swmrtools

extra:
  recipe-maintainers:
    - PeterC-DLS
    - jacobfilik
